import type { ActivityOption, DestinationSlug } from "@/lib/types";

/**
 * Extra curated experiences per destination so longer trips have enough variety
 * to pick from (merged in activity-service; not a live scrape).
 */
export function supplementalActivitiesForDestination(
  slug: DestinationSlug,
): ActivityOption[] {
  const s = (n: number, rest: Omit<ActivityOption, "id">): ActivityOption => ({
    id: `${slug}-sup-${n}`,
    ...rest,
  });

  const bySlug: Record<DestinationSlug, ActivityOption[]> = {
    goa: [
      s(1, {
        name: "Sunset river cruise",
        description: "Mandovi evening cruise with live music and coastal views.",
        duration: "3h",
        durationMinutes: 180,
        cost: 1200,
        tag: "Evening",
      }),
      s(2, {
        name: "Spice plantation & lunch",
        description: "Guided plantation walk, tasting, and traditional Goan meal.",
        duration: "4h",
        durationMinutes: 240,
        cost: 1600,
        tag: "Food",
      }),
      s(3, {
        name: "Dudhsagar Falls day",
        description: "Jeep ride and time at the falls — full-day monsoon classic.",
        duration: "8h",
        durationMinutes: 480,
        cost: 2800,
        tag: "Day trip",
      }),
      s(4, {
        name: "Lazy pool & resort morning",
        description: "Buffer breakfast and half-day downtime at your stay.",
        duration: "3h",
        durationMinutes: 180,
        cost: 0,
        tag: "Rest",
      }),
      s(5, {
        name: "Anjuna flea & sunset cliff",
        description: "Market browse, late lunch, and Vagator golden hour.",
        duration: "5h",
        durationMinutes: 300,
        cost: 1400,
        tag: "Popular",
      }),
    ],
    jaipur: [
      s(1, {
        name: "Nahargarh sunset",
        description: "Fort views over Pink City — best in late afternoon.",
        duration: "3h",
        durationMinutes: 180,
        cost: 900,
        tag: "Scenic",
      }),
      s(2, {
        name: "Jal Mahal photo & walk",
        description: "Waterside palace stop plus short lakeside stroll.",
        duration: "2h",
        durationMinutes: 120,
        cost: 600,
        tag: "Light",
      }),
      s(3, {
        name: "Block printing workshop",
        description: "Hands-on session with local artisans in a heritage studio.",
        duration: "3h",
        durationMinutes: 180,
        cost: 2200,
        tag: "Culture",
      }),
      s(4, {
        name: "Chokhi Dhani evening",
        description: "Rajasthani folk dinner, rides, and village-style entertainment.",
        duration: "4h",
        durationMinutes: 240,
        cost: 1800,
        tag: "Evening",
      }),
      s(5, {
        name: "Albert Hall & museum morning",
        description: "Calmer museum block before the fort crowds peak.",
        duration: "2h 30m",
        durationMinutes: 150,
        cost: 400,
        tag: "Heritage",
      }),
    ],
    udaipur: [
      s(1, {
        name: "Lake Pichola boat ride",
        description: "Shikara or shared boat — City Palace and islands from the water.",
        duration: "2h",
        durationMinutes: 120,
        cost: 800,
        tag: "Must try",
      }),
      s(2, {
        name: "Bagore Ki Haveli cultural show",
        description: "Evening puppet and folk dance show in a historic haveli.",
        duration: "2h",
        durationMinutes: 120,
        cost: 500,
        tag: "Evening",
      }),
      s(3, {
        name: "Chittorgarh day trip",
        description: "Full-day fort and history circuit from Udaipur.",
        duration: "9h",
        durationMinutes: 540,
        cost: 3500,
        tag: "Day trip",
      }),
      s(4, {
        name: "Village cycling morning",
        description: "Easy countryside loop with stops at crafts and farms.",
        duration: "4h",
        durationMinutes: 240,
        cost: 1900,
        tag: "Active",
      }),
      s(5, {
        name: "Rooftop dinner & lake views",
        description: "Reserve a terrace table for a slow multi-course night.",
        duration: "3h",
        durationMinutes: 180,
        cost: 2500,
        tag: "Couples",
      }),
    ],
    rishikesh: [
      s(1, {
        name: "Cliff jump & beach chill",
        description: "Guided jumps at safe spots plus riverside downtime.",
        duration: "3h",
        durationMinutes: 180,
        cost: 1200,
        tag: "Adventure",
      }),
      s(2, {
        name: "Morning yoga & pranayama",
        description: "Studio or riverside class with certified instructor.",
        duration: "2h",
        durationMinutes: 120,
        cost: 800,
        tag: "Wellness",
      }),
      s(3, {
        name: "Waterfall trek (Neer Garh)",
        description: "Moderate hike, swim stop, packed lunch style half-day.",
        duration: "5h",
        durationMinutes: 300,
        cost: 1000,
        tag: "Nature",
      }),
      s(4, {
        name: "Evening Ganga aarti focus",
        description: "Triveni or Parmarth — arrive early for a good seat.",
        duration: "2h",
        durationMinutes: 120,
        cost: 300,
        tag: "Spiritual",
      }),
    ],
    varanasi: [
      s(1, {
        name: "Evening Ganga aarti (Dashashwamedh)",
        description: "Grand ceremony from ghat steps or rooftop seats.",
        duration: "2h",
        durationMinutes: 120,
        cost: 800,
        tag: "Must visit",
      }),
      s(2, {
        name: "Silk weaving & sari lane",
        description: "Small workshops and authentic Banarasi craft stories.",
        duration: "3h",
        durationMinutes: 180,
        cost: 600,
        tag: "Culture",
      }),
      s(3, {
        name: "Blue Labyrinth photo walk",
        description: "Guided narrow-lane walk at gentler morning light.",
        duration: "3h",
        durationMinutes: 180,
        cost: 1200,
        tag: "Photo",
      }),
      s(4, {
        name: "Classical music at a gharana",
        description: "Evening sitar or vocal performance in an intimate setting.",
        duration: "2h",
        durationMinutes: 120,
        cost: 1500,
        tag: "Evening",
      }),
    ],
    andaman: [
      s(1, {
        name: "Kayak mangrove channel",
        description: "Guided paddle through calm backwaters.",
        duration: "3h",
        durationMinutes: 180,
        cost: 2200,
        tag: "Nature",
      }),
      s(2, {
        name: "Snorkelling add-on",
        description: "Shallow reef session with gear and boat support.",
        duration: "3h",
        durationMinutes: 180,
        cost: 3200,
        tag: "Water",
      }),
      s(3, {
        name: "Cellular Jail sound-and-light",
        description: "Evening show after a self-guided museum walk.",
        duration: "3h",
        durationMinutes: 180,
        cost: 600,
        tag: "History",
      }),
      s(4, {
        name: "Baratang limestone & mud volcano day",
        description: "Long day trip with boat and forest segments.",
        duration: "10h",
        durationMinutes: 600,
        cost: 4000,
        tag: "Day trip",
      }),
    ],
    darjeeling: [
      s(1, {
        name: "Toy train joy ride (Batasia)",
        description: "Short steam loop with loop views and photo stops.",
        duration: "3h",
        durationMinutes: 180,
        cost: 1500,
        tag: "Heritage",
      }),
      s(2, {
        name: "Himalayan Zoo & mountaineering institute",
        description: "Red panda route plus Everest museum context.",
        duration: "3h",
        durationMinutes: 180,
        cost: 500,
        tag: "Family",
      }),
      s(3, {
        name: "Japanese Peace Pagoda walk",
        description: "Quiet ridge walk and panoramic eastern Himalaya.",
        duration: "2h 30m",
        durationMinutes: 150,
        cost: 400,
        tag: "Calm",
      }),
      s(4, {
        name: "Tea tasting masterclass",
        description: "Cupping session at a working estate with take-home notes.",
        duration: "2h",
        durationMinutes: 120,
        cost: 1400,
        tag: "Food",
      }),
    ],
    leh: [
      s(1, {
        name: "Sham valley (Alchi) day",
        description: "Lower-altitude monasteries and Indus views — easier acclimatisation.",
        duration: "8h",
        durationMinutes: 480,
        cost: 3200,
        tag: "Scenic",
      }),
      s(2, {
        name: "Magnetic Hill & confluence stop",
        description: "Short photo route bundled with Sangam viewpoint.",
        duration: "4h",
        durationMinutes: 240,
        cost: 1800,
        tag: "Half day",
      }),
      s(3, {
        name: "Stok village & palace",
        description: "Gentle culture day without extreme passes.",
        duration: "5h",
        durationMinutes: 300,
        cost: 1400,
        tag: "Culture",
      }),
      s(4, {
        name: "Acclimatisation rest day",
        description: "Light walks, hydration, and sleep at altitude — doctor-recommended pacing.",
        duration: "2h",
        durationMinutes: 120,
        cost: 0,
        tag: "Rest",
      }),
    ],
    amritsar: [
      s(1, {
        name: "Partition Museum deep dive",
        description: "Narrative walkthrough — pair with a quiet lunch after.",
        duration: "3h",
        durationMinutes: 180,
        cost: 350,
        tag: "History",
      }),
      s(2, {
        name: "Gobindgarh Fort show",
        description: "Evening light show and bazaar stalls inside the fort.",
        duration: "3h",
        durationMinutes: 180,
        cost: 700,
        tag: "Evening",
      }),
      s(3, {
        name: "Village farm lunch",
        description: "Countryside drive, thali, and pottery or craft demo.",
        duration: "5h",
        durationMinutes: 300,
        cost: 2200,
        tag: "Food",
      }),
      s(4, {
        name: "Hall Bazaar shopping block",
        description: "Juttis, papad, and spices — budget an hour for haggling.",
        duration: "2h",
        durationMinutes: 120,
        cost: 500,
        tag: "Shopping",
      }),
    ],
    kozhikode: [
      s(1, {
        name: "Wayanad day (from Calicut)",
        description: "Long scenic drive to viewpoints and tea edges — start early.",
        duration: "12h",
        durationMinutes: 720,
        cost: 5500,
        tag: "Day trip",
      }),
      s(2, {
        name: "Sweet street crawl",
        description: "Halwa, banana chips, and jaggery coffee in SM Street lanes.",
        duration: "2h",
        durationMinutes: 120,
        cost: 600,
        tag: "Food",
      }),
      s(3, {
        name: "Beypore shipyard walk",
        description: "See uru boat building and harbour life.",
        duration: "3h",
        durationMinutes: 180,
        cost: 700,
        tag: "Heritage",
      }),
      s(4, {
        name: "Kappad landing viewpoint",
        description: "Historic beach where Vasco da Gama arrived — short drive.",
        duration: "4h",
        durationMinutes: 240,
        cost: 1400,
        tag: "History",
      }),
    ],
    chennai: [
      s(1, {
        name: "Mahabalipuram day",
        description: "Shore Temple, bas-reliefs, and beach breeze — easy day trip.",
        duration: "8h",
        durationMinutes: 480,
        cost: 2800,
        tag: "Heritage",
      }),
      s(2, {
        name: "Filter kaapi & bookshop morning",
        description: "Heritage cafes in Mylapore and Nungambakkam lanes.",
        duration: "3h",
        durationMinutes: 180,
        cost: 800,
        tag: "Slow",
      }),
      s(3, {
        name: "DakshinaChitra afternoon",
        description: "Open-air museum of South Indian crafts and homes.",
        duration: "4h",
        durationMinutes: 240,
        cost: 700,
        tag: "Culture",
      }),
      s(4, {
        name: "ECR coastal drive stop",
        description: "Pick a cove, seafood lunch, and wind back before dark.",
        duration: "6h",
        durationMinutes: 360,
        cost: 2200,
        tag: "Coastal",
      }),
    ],
    hyderabad: [
      s(1, {
        name: "Ramoji Film City day",
        description: "Full-day studio sets, rides, and sprawling backlots.",
        duration: "8h",
        durationMinutes: 480,
        cost: 2200,
        tag: "Family",
      }),
      s(2, {
        name: "Pearl & lac bazaar shopping",
        description: "Guided haggle-friendly loop near Charminar.",
        duration: "3h",
        durationMinutes: 180,
        cost: 500,
        tag: "Shopping",
      }),
      s(3, {
        name: "Hussain Sagar boat at dusk",
        description: "Short lake ride with Buddha island views.",
        duration: "2h",
        durationMinutes: 120,
        cost: 800,
        tag: "Evening",
      }),
      s(4, {
        name: "Salar Jung Museum deep dive",
        description: "One-way system-friendly highlights tour with audio option.",
        duration: "4h",
        durationMinutes: 240,
        cost: 350,
        tag: "Museum",
      }),
    ],
  };

  return bySlug[slug] ?? [];
}
