import type {
  DestinationContent,
  DestinationSlug,
  SourceCity,
  TripStyle,
} from "@/lib/types";

export const sourceCities: SourceCity[] = [
  "Bengaluru",
  "Mumbai",
  "Delhi",
  "Chennai",
  "Hyderabad",
  "Kolkata",
  "Pune",
  "Ahmedabad",
  "Kochi",
  "Lucknow",
  "Chandigarh",
  "Guwahati",
  "Bhubaneswar",
  "Indore",
  "Coimbatore",
];

export const tripStyles: TripStyle[] = [
  "Relaxed",
  "Adventure",
  "Food",
  "Nightlife",
  "Family",
  "Luxury",
];

/**
 * Destination catalog. Marketing content (name, summary, image, etc.) is
 * canonical. Flight / hotel / activity / transfer entries below are **curated
 * fallbacks** used only when the live Amadeus or OSRM APIs are not configured
 * or return empty results. The primary data path is through the service layer
 * at lib/services/.
 */
export const destinations: Record<DestinationSlug, DestinationContent> = {
  goa: {
    slug: "goa",
    name: "Goa",
    summary:
      "A breezy coastal escape with beaches, food, nightlife, and enough variety for both slow days and packed weekends.",
    bestFor: "Weekend breaks, beach days, food, nightlife",
    image:
      "https://images.unsplash.com/photo-1695453461885-bcecb1c64320?w=800&h=500&fit=crop&q=80&auto=format",
    imageCredit: "Chirayu Sharma",
    famousPlaces: [
      "Baga and Calangute",
      "Anjuna and Vagator",
      "Fort Aguada",
      "Fontainhas",
      "Candolim sunset stretch",
    ],
    outboundFlights: {
      Bengaluru: [
        {
          id: "blr-goi-1",
          label: "Morning nonstop",
          departTime: "07:10",
          arriveTime: "08:35",
          duration: "1h 25m",
          durationMinutes: 85,
          price: 4700,
          tag: "Best value",
          reason: "Saves most of day one without stretching budget.",
        },
        {
          id: "blr-goi-2",
          label: "Budget midday",
          departTime: "11:25",
          arriveTime: "12:55",
          duration: "1h 30m",
          durationMinutes: 90,
          price: 4100,
          tag: "Cheapest",
          reason: "Lowest fare if you do not mind reaching after lunch.",
        },
        {
          id: "blr-goi-3",
          label: "Fast early evening",
          departTime: "18:10",
          arriveTime: "19:30",
          duration: "1h 20m",
          durationMinutes: 80,
          price: 5600,
          tag: "Fastest",
          reason: "Quickest option for a smooth same-day arrival.",
        },
      ],
      Mumbai: [
        {
          id: "bom-goi-1",
          label: "Late morning nonstop",
          departTime: "10:00",
          arriveTime: "11:20",
          duration: "1h 20m",
          durationMinutes: 80,
          price: 3900,
          tag: "Best value",
          reason: "Easy timing and solid fare for a short Goa break.",
        },
        {
          id: "bom-goi-2",
          label: "Early budget hop",
          departTime: "06:35",
          arriveTime: "07:55",
          duration: "1h 20m",
          durationMinutes: 80,
          price: 3400,
          tag: "Cheapest",
          reason: "Lowest price if you are fine with an early airport start.",
        },
        {
          id: "bom-goi-3",
          label: "After-work departure",
          departTime: "18:50",
          arriveTime: "20:10",
          duration: "1h 20m",
          durationMinutes: 80,
          price: 4300,
          tag: "Smoothest",
          reason: "Good if you want to leave after work and still land same night.",
        },
      ],
      Delhi: [
        {
          id: "del-goi-1",
          label: "Early nonstop",
          departTime: "06:20",
          arriveTime: "08:55",
          duration: "2h 35m",
          durationMinutes: 155,
          price: 6200,
          tag: "Fastest",
          reason: "Best way to reach Goa early from Delhi.",
        },
        {
          id: "del-goi-2",
          label: "Balanced afternoon",
          departTime: "13:15",
          arriveTime: "15:55",
          duration: "2h 40m",
          durationMinutes: 160,
          price: 5600,
          tag: "Best value",
          reason: "Balanced fare and timing for a comfortable arrival.",
        },
        {
          id: "del-goi-3",
          label: "Night arrival",
          departTime: "19:40",
          arriveTime: "22:15",
          duration: "2h 35m",
          durationMinutes: 155,
          price: 5100,
          tag: "Cheapest",
          reason: "Best for budget if a late check-in is acceptable.",
        },
      ],
    },
    returnFlights: {
      Bengaluru: [
        {
          id: "goi-blr-1",
          label: "Late afternoon return",
          departTime: "16:30",
          arriveTime: "17:55",
          duration: "1h 25m",
          durationMinutes: 85,
          price: 4500,
          tag: "Best value",
          reason: "Lets you keep most of the final day without overspending.",
        },
        {
          id: "goi-blr-2",
          label: "Night return",
          departTime: "20:40",
          arriveTime: "22:05",
          duration: "1h 25m",
          durationMinutes: 85,
          price: 4300,
          tag: "Cheapest",
          reason: "Lowest return fare if you do not mind landing late.",
        },
      ],
      Mumbai: [
        {
          id: "goi-bom-1",
          label: "Early afternoon return",
          departTime: "14:05",
          arriveTime: "15:25",
          duration: "1h 20m",
          durationMinutes: 80,
          price: 3600,
          tag: "Best value",
          reason: "Easy return timing with good price control.",
        },
        {
          id: "goi-bom-2",
          label: "Evening return",
          departTime: "19:15",
          arriveTime: "20:35",
          duration: "1h 20m",
          durationMinutes: 80,
          price: 3900,
          tag: "Smoothest",
          reason: "Good for stretching the last day before flying back.",
        },
      ],
      Delhi: [
        {
          id: "goi-del-1",
          label: "Afternoon nonstop",
          departTime: "14:20",
          arriveTime: "16:55",
          duration: "2h 35m",
          durationMinutes: 155,
          price: 5900,
          tag: "Best value",
          reason: "A good return balance for a 4-day trip.",
        },
        {
          id: "goi-del-2",
          label: "Evening nonstop",
          departTime: "18:35",
          arriveTime: "21:10",
          duration: "2h 35m",
          durationMinutes: 155,
          price: 6200,
          tag: "Smoothest",
          reason: "Lets you keep the last day relaxed before heading home.",
        },
      ],
    },
    stays: [
      {
        id: "goa-stay-1",
        name: "Candolim Coast Stay",
        area: "Candolim",
        nightlyPrice: 4200,
        tag: "Best value",
        reason: "Balanced location for beaches, food, and easy movement.",
      },
      {
        id: "goa-stay-2",
        name: "Anjuna Social House",
        area: "Anjuna",
        nightlyPrice: 3600,
        tag: "Budget friendly",
        reason: "Great for nightlife and a younger trip vibe.",
      },
      {
        id: "goa-stay-3",
        name: "South Goa Retreat",
        area: "Colva",
        nightlyPrice: 5600,
        tag: "More comfortable",
        reason: "Quieter pace with a more relaxed stay experience.",
      },
    ],
    transfers: {
      Candolim: {
        id: "goa-transfer-candolim",
        label: "Airport to Candolim cab",
        duration: "55m",
        durationMinutes: 55,
        cost: 1400,
        reason: "Most direct option after landing.",
      },
      Anjuna: {
        id: "goa-transfer-anjuna",
        label: "Airport to Anjuna cab",
        duration: "1h 10m",
        durationMinutes: 70,
        cost: 1650,
        reason: "Longer ride, but easiest with luggage.",
      },
      Colva: {
        id: "goa-transfer-colva",
        label: "Airport to Colva cab",
        duration: "40m",
        durationMinutes: 40,
        cost: 1100,
        reason: "Smooth arrival with shorter transfer time.",
      },
    },
    activities: [
      {
        id: "goa-act-1",
        name: "Beach day",
        description: "A light day around Candolim or Vagator with sunset built in.",
        duration: "5h",
        durationMinutes: 300,
        cost: 1800,
        tag: "Popular",
      },
      {
        id: "goa-act-2",
        name: "Food-focused day",
        description: "Cafe hop, seafood lunch, and a slower evening around Fontainhas.",
        duration: "4h",
        durationMinutes: 240,
        cost: 2200,
        tag: "Must try",
      },
      {
        id: "goa-act-3",
        name: "Sightseeing day",
        description: "Fort Aguada, old quarters, and a scenic sunset stop.",
        duration: "5h 30m",
        durationMinutes: 330,
        cost: 1600,
        tag: "Must visit",
      },
    ],
  },
  jaipur: {
    slug: "jaipur",
    name: "Jaipur",
    summary:
      "A rich city break with forts, markets, food, and heritage stays that fit well into a 3 to 5 day plan.",
    bestFor: "Culture, food, shopping, short heritage trips",
    image:
      "https://images.unsplash.com/photo-1524229321985-1e1989075d9b?w=800&h=500&fit=crop&q=80&auto=format",
    imageCredit: "Annie Spratt",
    famousPlaces: [
      "Amer Fort",
      "Hawa Mahal",
      "City Palace",
      "Nahargarh Fort",
      "Bapu Bazaar",
    ],
    outboundFlights: {
      Bengaluru: [
        {
          id: "blr-jai-1",
          label: "Morning nonstop",
          departTime: "07:40",
          arriveTime: "10:10",
          duration: "2h 30m",
          durationMinutes: 150,
          price: 6400,
          tag: "Best value",
          reason: "Strong timing for reaching Jaipur before lunch.",
        },
        {
          id: "blr-jai-2",
          label: "Budget afternoon",
          departTime: "13:25",
          arriveTime: "16:00",
          duration: "2h 35m",
          durationMinutes: 155,
          price: 5700,
          tag: "Cheapest",
          reason: "A good budget pick if day one can start slower.",
        },
      ],
      Mumbai: [
        {
          id: "bom-jai-1",
          label: "Early nonstop",
          departTime: "08:15",
          arriveTime: "10:05",
          duration: "1h 50m",
          durationMinutes: 110,
          price: 4600,
          tag: "Best value",
          reason: "Short travel time and an easy city arrival.",
        },
        {
          id: "bom-jai-2",
          label: "Night arrival",
          departTime: "19:10",
          arriveTime: "21:00",
          duration: "1h 50m",
          durationMinutes: 110,
          price: 4100,
          tag: "Cheapest",
          reason: "Best fare if a late hotel check-in is fine.",
        },
      ],
      Delhi: [
        {
          id: "del-jai-1",
          label: "Fast hop",
          departTime: "09:25",
          arriveTime: "10:20",
          duration: "55m",
          durationMinutes: 55,
          price: 3500,
          tag: "Fastest",
          reason: "Quickest way to turn Delhi into a Jaipur getaway.",
        },
        {
          id: "del-jai-2",
          label: "Best value hop",
          departTime: "12:10",
          arriveTime: "13:05",
          duration: "55m",
          durationMinutes: 55,
          price: 3200,
          tag: "Best value",
          reason: "Good balance of timing and fare.",
        },
      ],
    },
    returnFlights: {
      Bengaluru: [
        {
          id: "jai-blr-1",
          label: "Evening return",
          departTime: "18:10",
          arriveTime: "20:40",
          duration: "2h 30m",
          durationMinutes: 150,
          price: 6100,
          tag: "Best value",
          reason: "Keeps most of your final Jaipur day free.",
        },
      ],
      Mumbai: [
        {
          id: "jai-bom-1",
          label: "Afternoon return",
          departTime: "15:45",
          arriveTime: "17:35",
          duration: "1h 50m",
          durationMinutes: 110,
          price: 4300,
          tag: "Best value",
          reason: "Simple timing and easy return.",
        },
      ],
      Delhi: [
        {
          id: "jai-del-1",
          label: "Evening hop",
          departTime: "19:40",
          arriveTime: "20:35",
          duration: "55m",
          durationMinutes: 55,
          price: 3300,
          tag: "Smoothest",
          reason: "Lets you finish a full day before heading back.",
        },
      ],
    },
    stays: [
      {
        id: "jai-stay-1",
        name: "Pink City Courtyard",
        area: "Bani Park",
        nightlyPrice: 3900,
        tag: "Best value",
        reason: "Central enough for markets and fort access.",
      },
      {
        id: "jai-stay-2",
        name: "Old City Haveli",
        area: "Pink City",
        nightlyPrice: 5100,
        tag: "More comfortable",
        reason: "Closer to heritage sights and classic Jaipur feel.",
      },
      {
        id: "jai-stay-3",
        name: "Budget Bazaar Stay",
        area: "MI Road",
        nightlyPrice: 3200,
        tag: "Budget friendly",
        reason: "Good if you want to stay central without overspending.",
      },
    ],
    transfers: {
      "Bani Park": {
        id: "jai-transfer-bani",
        label: "Airport to Bani Park cab",
        duration: "35m",
        durationMinutes: 35,
        cost: 800,
        reason: "Direct transfer with no planning friction.",
      },
      "Pink City": {
        id: "jai-transfer-pink",
        label: "Airport to Pink City cab",
        duration: "40m",
        durationMinutes: 40,
        cost: 900,
        reason: "Best for getting straight into the heritage core.",
      },
      "MI Road": {
        id: "jai-transfer-mi",
        label: "Airport to MI Road cab",
        duration: "30m",
        durationMinutes: 30,
        cost: 750,
        reason: "A short and simple city arrival.",
      },
    },
    activities: [
      {
        id: "jai-act-1",
        name: "Sightseeing day",
        description: "Amer Fort, Hawa Mahal, and a slower old-city walk.",
        duration: "6h",
        durationMinutes: 360,
        cost: 1800,
        tag: "Must visit",
      },
      {
        id: "jai-act-2",
        name: "Food and market day",
        description: "Street food, local sweets, and market browsing.",
        duration: "4h 30m",
        durationMinutes: 270,
        cost: 1500,
        tag: "Popular",
      },
    ],
  },
  udaipur: {
    slug: "udaipur",
    name: "Udaipur",
    summary:
      "A slower lake city break with scenic stays, relaxed sightseeing, and a premium feel without needing a packed itinerary.",
    bestFor: "Slow travel, couples, scenic stays, relaxed heritage trips",
    image:
      "https://images.unsplash.com/photo-1706961121527-4017856774c7?w=800&h=500&fit=crop&q=80&auto=format",
    imageCredit: "Abhishek R",
    famousPlaces: [
      "City Palace",
      "Lake Pichola",
      "Sajjangarh",
      "Bagore Ki Haveli",
      "Fateh Sagar",
    ],
    outboundFlights: {
      Bengaluru: [
        {
          id: "blr-udr-1",
          label: "Morning one-stop",
          departTime: "06:50",
          arriveTime: "10:45",
          duration: "3h 55m",
          durationMinutes: 235,
          price: 6900,
          tag: "Best value",
          reason: "Good overall timing for a scenic 4-day trip.",
        },
      ],
      Mumbai: [
        {
          id: "bom-udr-1",
          label: "Late morning nonstop",
          departTime: "10:20",
          arriveTime: "11:45",
          duration: "1h 25m",
          durationMinutes: 85,
          price: 4300,
          tag: "Best value",
          reason: "Simple and efficient option for a short getaway.",
        },
      ],
      Delhi: [
        {
          id: "del-udr-1",
          label: "Morning nonstop",
          departTime: "08:15",
          arriveTime: "09:35",
          duration: "1h 20m",
          durationMinutes: 80,
          price: 3900,
          tag: "Best value",
          reason: "Great for reaching Udaipur early with low hassle.",
        },
      ],
    },
    returnFlights: {
      Bengaluru: [
        {
          id: "udr-blr-1",
          label: "Evening one-stop",
          departTime: "17:10",
          arriveTime: "21:05",
          duration: "3h 55m",
          durationMinutes: 235,
          price: 6700,
          tag: "Best value",
          reason: "Lets you keep the final day open and relaxed.",
        },
      ],
      Mumbai: [
        {
          id: "udr-bom-1",
          label: "Afternoon nonstop",
          departTime: "15:10",
          arriveTime: "16:35",
          duration: "1h 25m",
          durationMinutes: 85,
          price: 4200,
          tag: "Smoothest",
          reason: "Easy return without stretching the day too much.",
        },
      ],
      Delhi: [
        {
          id: "udr-del-1",
          label: "Evening nonstop",
          departTime: "18:40",
          arriveTime: "20:00",
          duration: "1h 20m",
          durationMinutes: 80,
          price: 3700,
          tag: "Best value",
          reason: "Comfortable final-day timing with a sensible fare.",
        },
      ],
    },
    stays: [
      {
        id: "udr-stay-1",
        name: "Lake View Stay",
        area: "Lal Ghat",
        nightlyPrice: 4800,
        tag: "Best value",
        reason: "Good lake access with strong overall trip feel.",
      },
      {
        id: "udr-stay-2",
        name: "Heritage Courtyard",
        area: "Ambamata",
        nightlyPrice: 3900,
        tag: "Budget friendly",
        reason: "A calmer area with lower nightly cost.",
      },
    ],
    transfers: {
      "Lal Ghat": {
        id: "udr-transfer-lalghat",
        label: "Airport to Lal Ghat cab",
        duration: "45m",
        durationMinutes: 45,
        cost: 950,
        reason: "Direct transfer into the old-city lake area.",
      },
      Ambamata: {
        id: "udr-transfer-ambamata",
        label: "Airport to Ambamata cab",
        duration: "40m",
        durationMinutes: 40,
        cost: 850,
        reason: "Simple and slightly cheaper than core old-city drop-offs.",
      },
    },
    activities: [
      {
        id: "udr-act-1",
        name: "Lake and palace day",
        description: "A slower scenic day built around the palace zone and a lake view evening.",
        duration: "5h",
        durationMinutes: 300,
        cost: 1900,
        tag: "Must visit",
      },
      {
        id: "udr-act-2",
        name: "Relaxed explore day",
        description: "A lighter day for cafes, city walks, and a sunset point.",
        duration: "4h",
        durationMinutes: 240,
        cost: 1400,
        tag: "Popular",
      },
    ],
  },
  rishikesh: {
    slug: "rishikesh",
    name: "Rishikesh",
    summary:
      "The yoga capital of the world — a Ganges-side town for rafting, ashrams, suspension bridges, and spiritual calm.",
    bestFor: "Adventure, yoga, spiritual trips, rafting",
    image:
      "https://images.unsplash.com/photo-1720819029162-8500607ae232?w=800&h=500&fit=crop&q=80&auto=format",
    imageCredit: "Unsplash",
    famousPlaces: ["Laxman Jhula", "Ram Jhula", "Triveni Ghat", "Beatles Ashram", "Neer Garh Waterfall"],
    activities: [
      { id: "rsh-act-1", name: "White-water rafting", description: "16 km rafting on the Ganges with rapids from grade I to IV.", duration: "4h", durationMinutes: 240, cost: 2000, tag: "Must try" },
      { id: "rsh-act-2", name: "Ashram and ghat walk", description: "Visit the Beatles Ashram, Triveni Ghat aarti, and riverside yoga.", duration: "5h", durationMinutes: 300, cost: 800, tag: "Popular" },
    ],
  },
  varanasi: {
    slug: "varanasi",
    name: "Varanasi",
    summary:
      "India's oldest city — an intense, spiritual, one-of-a-kind experience along the ghats of the Ganges.",
    bestFor: "Culture, spiritual trips, photography, food",
    image:
      "https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=800&h=500&fit=crop&q=80&auto=format",
    imageCredit: "Debashis Biswas",
    famousPlaces: ["Dashashwamedh Ghat", "Kashi Vishwanath", "Assi Ghat", "Sarnath", "Manikarnika Ghat"],
    activities: [
      { id: "vns-act-1", name: "Morning boat ride", description: "Sunrise boat ride along the ghats — the quintessential Varanasi experience.", duration: "2h", durationMinutes: 120, cost: 1500, tag: "Must try" },
      { id: "vns-act-2", name: "Ghat walk and street food", description: "Walk the ghats, visit temples, and try local chaat and lassi.", duration: "5h", durationMinutes: 300, cost: 1000, tag: "Popular" },
      { id: "vns-act-3", name: "Sarnath day trip", description: "Visit the place where Buddha gave his first sermon.", duration: "4h", durationMinutes: 240, cost: 1200, tag: "Must visit" },
    ],
  },
  andaman: {
    slug: "andaman",
    name: "Andaman",
    summary:
      "Crystal-clear waters, white sand beaches, and coral reefs — India's tropical island paradise in the Bay of Bengal.",
    bestFor: "Beach holidays, snorkeling, scuba diving, couples",
    image:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=500&fit=crop&q=80&auto=format",
    imageCredit: "Sean O.",
    famousPlaces: ["Radhanagar Beach", "Cellular Jail", "Havelock Island", "Neil Island", "Ross Island"],
    activities: [
      { id: "and-act-1", name: "Scuba diving at Havelock", description: "Dive with colorful coral reefs and tropical fish at Elephant Beach.", duration: "4h", durationMinutes: 240, cost: 4500, tag: "Must try" },
      { id: "and-act-2", name: "Beach hopping day", description: "Radhanagar, Vijaynagar, and a sunset at Kalapathar Beach.", duration: "6h", durationMinutes: 360, cost: 1500, tag: "Popular" },
    ],
  },
  darjeeling: {
    slug: "darjeeling",
    name: "Darjeeling",
    summary:
      "Tea gardens, Kanchenjunga views, the toy train, and a nostalgic hill-town pace that slows you down in the best way.",
    bestFor: "Nature, tea lovers, couples, peaceful getaways",
    image:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=500&fit=crop&q=80&auto=format",
    imageCredit: "Samuel Ferrara",
    famousPlaces: ["Tiger Hill", "Batasia Loop", "Peace Pagoda", "Tea Gardens", "Darjeeling Mall"],
    activities: [
      { id: "drj-act-1", name: "Tiger Hill sunrise", description: "Early morning drive to see Kanchenjunga lit up at sunrise.", duration: "3h", durationMinutes: 180, cost: 1200, tag: "Must visit" },
      { id: "drj-act-2", name: "Tea estate tour", description: "Walk through Happy Valley tea garden and taste fresh Darjeeling tea.", duration: "3h", durationMinutes: 180, cost: 900, tag: "Popular" },
    ],
  },
  leh: {
    slug: "leh",
    name: "Leh Ladakh",
    summary:
      "High-altitude desert landscapes, monasteries, Pangong Lake, and some of the most dramatic scenery on the planet.",
    bestFor: "Adventure, road trips, photography, nature",
    image:
      "https://images.unsplash.com/photo-1606857090627-27ca46667290?w=800&h=500&fit=crop&q=80&auto=format",
    imageCredit: "Ken S",
    famousPlaces: ["Pangong Lake", "Khardung La", "Thiksey Monastery", "Shanti Stupa", "Magnetic Hill"],
    activities: [
      { id: "leh-act-1", name: "Pangong Lake day trip", description: "A full-day drive to the surreal blue Pangong Tso lake.", duration: "10h", durationMinutes: 600, cost: 4000, tag: "Must visit" },
      { id: "leh-act-2", name: "Monastery circuit", description: "Visit Thiksey, Hemis, and Shey monasteries with mountain backdrops.", duration: "5h", durationMinutes: 300, cost: 1500, tag: "Popular" },
    ],
  },
  amritsar: {
    slug: "amritsar",
    name: "Amritsar",
    summary:
      "Home of the Golden Temple and the Wagah Border — a city of deep faith, history, and unbeatable Punjabi food.",
    bestFor: "Culture, food, spiritual trips, family",
    image:
      "https://images.unsplash.com/photo-1514222134-b57cbb8ce073?w=800&h=500&fit=crop&q=80&auto=format",
    imageCredit: "Amardeep Singh",
    famousPlaces: ["Golden Temple", "Jallianwala Bagh", "Wagah Border", "Partition Museum", "Hall Bazaar"],
    activities: [
      { id: "asr-act-1", name: "Golden Temple experience", description: "Visit the serene Golden Temple, volunteer at the langar, and evening palki sahib ceremony.", duration: "4h", durationMinutes: 240, cost: 0, tag: "Must visit" },
      { id: "asr-act-2", name: "Wagah Border ceremony", description: "Watch the electrifying flag-lowering ceremony at the India-Pakistan border.", duration: "4h", durationMinutes: 240, cost: 800, tag: "Popular" },
      { id: "asr-act-3", name: "Food trail", description: "Kulche chole, amritsari fish, lassi, and jalebi at legendary local joints.", duration: "3h", durationMinutes: 180, cost: 1200, tag: "Must try" },
    ],
  },
  kozhikode: {
    slug: "kozhikode",
    name: "Kozhikode (Calicut)",
    summary:
      "Arabian Sea sunsets, historic spice port lanes, legendary Malabar food, and easy access to Wayanad day trips.",
    bestFor: "Food lovers, beach, history, slow travel",
    image:
      "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=500&fit=crop&q=80&auto=format",
    imageCredit: "Unsplash",
    famousPlaces: [
      "Kozhikode Beach",
      "Mananchira Square",
      "Beypore port",
      "Kappad Beach",
      "SM Street food",
    ],
    activities: [
      {
        id: "ccj-act-1",
        name: "Sunset at Kozhikode Beach",
        description: "Promenade walk, street snacks, and fishing harbour bustle.",
        duration: "3h",
        durationMinutes: 180,
        cost: 500,
        tag: "Popular",
      },
      {
        id: "ccj-act-2",
        name: "Malabar food trail",
        description: "Guided evening of biryani, halwa, and coastal small plates.",
        duration: "4h",
        durationMinutes: 240,
        cost: 1800,
        tag: "Must try",
      },
    ],
  },
  chennai: {
    slug: "chennai",
    name: "Chennai",
    summary:
      "Marina mornings, filter coffee, Carnatic culture, ancient temples, and a long Bay of Bengal coastline.",
    bestFor: "Culture, food, beaches, city breaks",
    image:
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&h=500&fit=crop&q=80&auto=format",
    imageCredit: "Raj Rana",
    famousPlaces: [
      "Marina Beach",
      "Kapaleeshwarar Temple",
      "Fort St George",
      "San Thome Basilica",
      "ECR drive",
    ],
    activities: [
      {
        id: "maa-act-1",
        name: "Mylapore temple & market",
        description: "Morning gopuram visit and flower-market lanes with coffee stops.",
        duration: "4h",
        durationMinutes: 240,
        cost: 700,
        tag: "Culture",
      },
      {
        id: "maa-act-2",
        name: "Marina walk & lighthouse",
        description: "Long shoreline stroll and historic lighthouse area.",
        duration: "3h",
        durationMinutes: 180,
        cost: 300,
        tag: "Popular",
      },
    ],
  },
  hyderabad: {
    slug: "hyderabad",
    name: "Hyderabad",
    summary:
      "Charminar nights, Hyderabadi biryani, Golconda Fort, Ramoji Film City, and a fast-growing metro with deep Deccan roots.",
    bestFor: "Food, history, family, long weekends",
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=500&fit=crop&q=80&auto=format",
    imageCredit: "Unsplash",
    famousPlaces: [
      "Charminar",
      "Golconda Fort",
      "Hussain Sagar",
      "Qutb Shahi tombs",
      "Laad Bazaar",
    ],
    activities: [
      {
        id: "hyd-act-1",
        name: "Old City food walk",
        description: "Biryani, haleem (seasonal), Irani chai, and Charminar by night.",
        duration: "4h",
        durationMinutes: 240,
        cost: 1500,
        tag: "Must try",
      },
      {
        id: "hyd-act-2",
        name: "Golconda sound & light",
        description: "Fort exploration plus evening show when running.",
        duration: "5h",
        durationMinutes: 300,
        cost: 1200,
        tag: "History",
      },
    ],
  },
};

export function getDestination(slug: DestinationSlug) {
  return destinations[slug];
}
